Repository eclipse-vertx/vertx-auth, pull requests merged in 2020-10, with the labels that each got.

#420 Doc: Add missing auth helpers
  vertx-auth-oauth2/src/main/asciidoc/index.adoc
Labels: Hacktoberfest

#421 Add GitLab factory
  vertx-auth-oauth2/src/main/asciidoc/index.adoc
  vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/providers/GitLabAuth.java
Labels: Hacktoberfest, enhancement

#424 Fixes #423
  vertx-auth-common/src/main/asciidoc/dataobjects.adoc
  vertx-auth-common/src/main/generated/io/vertx/ext/auth/KeyStoreOptionsConverter.java
  vertx-auth-common/src/main/java/io/vertx/ext/auth/KeyStoreOptions.java
  vertx-auth-jwt/src/main/generated/io/vertx/ext/auth/jwt/JWTAuthOptionsConverter.java
  vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/JWTAuthOptions.java
  vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/impl/JWTAuthProviderImpl.java
Labels: enhancement

#426 Initial implementation of apple attestation
  vertx-auth-webauthn/README.adoc
  vertx-auth-webauthn/src/main/asciidoc/index.adoc
  vertx-auth-webauthn/src/main/java/io/vertx/ext/auth/webauthn/impl/attestation/AppleAttestation.java
  vertx-auth-webauthn/src/main/resources/META-INF/services/io.vertx.ext.auth.webauthn.impl.attestation.Attestation
  vertx-auth-webauthn/src/test/java/io/vertx/ext/auth/webauthn/impl/attestation/AttestationTest.java
Labels: enhancement
